# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-25 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Billing_Profile',
            new_name='billing_profile',
        ),
    ]
